Gem::Specification.new do |s|
  s.name = 'omah_search'
  s.version = '0.1.0'
  s.summary = 'Searches the email headers from the Offine Mail Helper (OMAH) database generated by the omah-plugin-sqlite.'
  s.authors = ['James Robertson']
  s.files = Dir['lib/omah_search.rb']
  s.add_runtime_dependency('sqlite3', '~> 1.3', '>=1.3.11')
  s.add_runtime_dependency('dynarex', '~> 1.7', '>=1.7.8')
  s.signing_key = '../privatekeys/omah_search.pem'
  s.cert_chain  = ['gem-public_cert.pem']
  s.license = 'MIT'
  s.email = 'james@r0bertson.co.uk'
  s.homepage = 'https://github.com/jrobertson/omah_search'
end
